{{ $project := .Values.projects.infrastructure }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $project.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  project: {{ $project.name }}
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      {{- if $project.serverSideApply}}
      - ServerSideApply=true
      {{- end}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  source:
    path: {{ tpl $project.path . }}
    repoURL: {{ $project.repoUrl }}
    targetRevision: {{ $project.branch }}
    helm:
      values: |
        global:
          {{- tpl (.Values.global | toYaml) . | nindent 10}}
      valueFiles:
        - values.yaml
        {{- if .Values.global.terraformValues.stage }}
        - values-{{ .Values.global.terraformValues.stage }}.yaml
        {{- end}}