{{ $project := .Values.projects.infrastructure }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-{{ $project.name }}
  labels:
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: argocd
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  url: {{ $project.repoUrl | b64enc }}
  name: {{ printf $project.name | b64enc }}
  type: {{ printf "git" | b64enc }}
  {{- if ne .Values.projects.gitToken.password  "" }}
  password: {{ printf .Values.projects.gitToken.password | b64enc }}
  username: {{ printf .Values.projects.gitToken.name | b64enc }}
  {{else}}
  {{- if ne .Values.projects.repoPrivateKeyBase64Encoded "" }}
  sshPrivateKey: {{ printf .Values.projects.repoPrivateKeyBase64Encoded }}
  {{- end }}
  {{- end }}
