argo-cd:
  controller:
    env:
      - name: "TZ"
        value: "Europe/Berlin"
      - name: "ARGOCD_GPG_ENABLED"
        value: "false"
    logFormat: "json"
  crds:
    install: "false"
  dex:
    env:
      - name: "TZ"
        value: "Europe/Berlin"
      - name: "ARGOCD_GPG_ENABLED"
        value: "false"
    logFormat: "json"
  notifications:
    enabled: "false"
  repoServer:
    env:
      - name: "TZ"
        value: "Europe/Berlin"
      - name: "ARGOCD_GPG_ENABLED"
        value: "false"
    logFormat: "json"
  server:
    env:
      - name: "TZ"
        value: "Europe/Berlin"
      - name: "ARGOCD_GPG_ENABLED"
        value: "false"
    extraArgs:
      - "--insecure"
      - "--rootpath=/argocd"
      - "--basehref=/argocd"
    logFormat: json
projects:
#  infrastructure-charts:
#    projectValues:
#      # Set this to enable stage values.yaml
#      stage:
#    serverSideApply: "false"
#    git:
#      username: "ARGOCD_GIT_ACCESS_TOKEN"
#      password: "SET_BY_TERRAFORM"
#      repoUrl: "SET_BY_TERRAFORM"
#      branch: "main"
#      path: "infrastructure-charts"
#      repoPrivateKeyBase64Encoded:
#    allowedUrls:
#      - "SET_BY_TERRAFORM"
